### ISSUE TITLE
`docs` directory probably didn't want to be checked in...?

### ISSUE THREAD

**Issue by shepmaster** [atorstling/corsware#5]

**Comment by atorstling** [comment]
I agree, but I've done it that way to be able to host the documentation through github pages, without having to create a separate repo for it.

**Comment by shepmaster** [comment]
The normal way I've seen that done is to [create a separate `gh-pages` branch that has a completely different root](https://help.github.com/articles/user-organization-and-project-pages/#project-pages).

**Comment by atorstling** [comment]
Thanks. I'll consider doing that. I have some built-up resentment towards branches with totally different content though... That's not what branches are for! </rant> :)

**Comment by shepmaster** [comment]
Sure. Feel free to close as you'd like. I mostly found it annoying because I was trying to grep for instances of "iron" and mostly got results from this directory.

**Comment by atorstling** [comment]
Ah. Makes sense. I will get with the times and create a separate branch then :)

**Comment by shepmaster** [comment]
> to host the documentation

I'm also sure you're aware, but just in case, docs.rs is [already hosting your docs](https://docs.rs/corsware/0.2.0/corsware/).

**Comment by atorstling** [comment]
Removed docs per you suggestion in a43a70c6f4105b846c4b0abeb4bb3898e50ab477
